# Generated by Django 5.0.7 on 2024-08-08 18:59

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth.Group')
    Group.objects.create(name='Active Users')

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth.Group')
    Group.objects.filter(name='Active Users').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_normalmodel"),
    ]

    operations = [migrations.RunPython(create_groups, remove_groups)]
